copyright: Copyright &copy; 2023-2024 <a href="https://github.com/xiaoxuan6/weekly">xiaoxuan6's</a>.
extra:
  social:
  - icon: fontawesome/solid/blog
    link: https://xiaoxuan6.github.io
  - icon: fontawesome/brands/github-alt
    link: https://github.com/xiaoxuan6
extra_css:
- static/css/simpleLightbox.css
- static/css/custom.css
extra_javascript:
- https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
- static/js/index.js
- static/js/simpleLightbox.js
- static/js/custom.js
markdown_extensions:
- markdown.extensions.attr_list
nav:
- 2024 年刊:
  - 第148期（2024-12-15）.md: ./2024/12/第148期（2024-12-15）.md
  - 第147期（2024-12-14）.md: ./2024/12/第147期（2024-12-14）.md
  - 第146期（2024-12-13）.md: ./2024/12/第146期（2024-12-13）.md
  - 第145期（2024-12-12）.md: ./2024/12/第145期（2024-12-12）.md
  - 第144期（2024-12-09）.md: ./2024/12/第144期（2024-12-09）.md
  - 第143期（2024-12-06）.md: ./2024/12/第143期（2024-12-06）.md
  - 第142期（2024-12-02）.md: ./2024/12/第142期（2024-12-02）.md
  - 第141期（2024-11-30）.md: ./2024/11/第141期（2024-11-30）.md
  - 第140期（2024-11-26）.md: ./2024/11/第140期（2024-11-26）.md
  - 第139期（2024-11-25）.md: ./2024/11/第139期（2024-11-25）.md
  - 第138期（2024-11-21）.md: ./2024/11/第138期（2024-11-21）.md
  - 第137期（2024-11-20）.md: ./2024/11/第137期（2024-11-20）.md
  - 第136期（2024-11-18）.md: ./2024/11/第136期（2024-11-18）.md
  - 第135期（2024-11-17）.md: ./2024/11/第135期（2024-11-17）.md
  - 第134期（2024-11-16）.md: ./2024/11/第134期（2024-11-16）.md
  - 第133期（2024-11-14）.md: ./2024/11/第133期（2024-11-14）.md
  - 第132期（2024-11-12）.md: ./2024/11/第132期（2024-11-12）.md
  - 第131期（2024-11-11）.md: ./2024/11/第131期（2024-11-11）.md
  - 第130期（2024-11-10）.md: ./2024/11/第130期（2024-11-10）.md
  - 第129期（2024-11-09）.md: ./2024/11/第129期（2024-11-09）.md
  - 第128期（2024-11-07）.md: ./2024/11/第128期（2024-11-07）.md
  - 第127期（2024-11-06）.md: ./2024/11/第127期（2024-11-06）.md
  - 第126期（2024-11-04）.md: ./2024/11/第126期（2024-11-04）.md
  - 第125期（2024-11-03）.md: ./2024/11/第125期（2024-11-03）.md
  - 第124期（2024-11-02）.md: ./2024/11/第124期（2024-11-02）.md
  - 第123期（2024-10-29）.md: ./2024/10/第123期（2024-10-29）.md
  - 第122期（2024-10-27）.md: ./2024/10/第122期（2024-10-27）.md
  - 第121期（2024-10-26）.md: ./2024/10/第121期（2024-10-26）.md
  - 第120期（2024-10-24）.md: ./2024/10/第120期（2024-10-24）.md
  - 第119期（2024-10-22）.md: ./2024/10/第119期（2024-10-22）.md
  - 第118期（2024-10-19）.md: ./2024/10/第118期（2024-10-19）.md
  - 第117期（2024-10-18）.md: ./2024/10/第117期（2024-10-18）.md
  - 第116期（2024-10-17）.md: ./2024/10/第116期（2024-10-17）.md
  - 第115期（2024-10-15）.md: ./2024/10/第115期（2024-10-15）.md
  - 第114期（2024-10-14）.md: ./2024/10/第114期（2024-10-14）.md
  - 第113期（2024-10-13）.md: ./2024/10/第113期（2024-10-13）.md
  - 第112期（2024-10-11）.md: ./2024/10/第112期（2024-10-11）.md
  - 第111期（2024-10-10）.md: ./2024/10/第111期（2024-10-10）.md
  - 第110期（2024-10-05）.md: ./2024/10/第110期（2024-10-05）.md
  - 第109期（2024-10-03）.md: ./2024/10/第109期（2024-10-03）.md
  - 第108期（2024-10-02）.md: ./2024/10/第108期（2024-10-02）.md
  - 第107期（2024-10-01）.md: ./2024/10/第107期（2024-10-01）.md
  - 第106期（2024-09-30）.md: ./2024/09/第106期（2024-09-30）.md
  - 第105期（2024-09-28）.md: ./2024/09/第105期（2024-09-28）.md
  - 第104期（2024-09-24）.md: ./2024/09/第104期（2024-09-24）.md
  - 第103期（2024-09-17）.md: ./2024/09/第103期（2024-09-17）.md
  - 第102期（2024-09-15）.md: ./2024/09/第102期（2024-09-15）.md
  - 第101期（2024-09-14）.md: ./2024/09/第101期（2024-09-14）.md
  - 第100期（2024-09-13）.md: ./2024/09/第100期（2024-09-13）.md
  - 第99期（2024-09-11）.md: ./2024/09/第99期（2024-09-11）.md
  - 第98期（2024-09-10）.md: ./2024/09/第98期（2024-09-10）.md
  - 第97期（2024-09-08）.md: ./2024/09/第97期（2024-09-08）.md
  - 第96期（2024-09-07）.md: ./2024/09/第96期（2024-09-07）.md
  - 第95期（2024-09-05）.md: ./2024/09/第95期（2024-09-05）.md
  - 第94期（2024-09-04）.md: ./2024/09/第94期（2024-09-04）.md
  - 第93期（2024-09-03）.md: ./2024/09/第93期（2024-09-03）.md
  - 第92期（2024-09-02）.md: ./2024/09/第92期（2024-09-02）.md
  - 第91期（2024-08-30）.md: ./2024/08/第91期（2024-08-30）.md
  - 第90期（2024-08-29）.md: ./2024/08/第90期（2024-08-29）.md
  - 第89期（2024-08-28）.md: ./2024/08/第89期（2024-08-28）.md
  - 第88期（2024-08-27）.md: ./2024/08/第88期（2024-08-27）.md
  - 第87期（2024-08-24）.md: ./2024/08/第87期（2024-08-24）.md
  - 第86期（2024-08-23）.md: ./2024/08/第86期（2024-08-23）.md
  - 第85期（2024-08-21）.md: ./2024/08/第85期（2024-08-21）.md
  - 第84期（2024-08-20）.md: ./2024/08/第84期（2024-08-20）.md
  - 第83期（2024-08-19）.md: ./2024/08/第83期（2024-08-19）.md
  - 第82期（2024-08-18）.md: ./2024/08/第82期（2024-08-18）.md
  - 第81期（2024-08-17）.md: ./2024/08/第81期（2024-08-17）.md
  - 第80期（2024-08-14）.md: ./2024/08/第80期（2024-08-14）.md
  - 第79期（2024-08-13）.md: ./2024/08/第79期（2024-08-13）.md
  - 第78期（2024-08-11）.md: ./2024/08/第78期（2024-08-11）.md
  - 第77期（2024-08-09）.md: ./2024/08/第77期（2024-08-09）.md
  - 第76期（2024-08-08）.md: ./2024/08/第76期（2024-08-08）.md
  - 第75期（2024-08-06）.md: ./2024/08/第75期（2024-08-06）.md
  - 第74期（2024-08-04）.md: ./2024/08/第74期（2024-08-04）.md
  - 第73期（2024-08-02）.md: ./2024/08/第73期（2024-08-02）.md
  - 第72期（2024-07-29）.md: ./2024/07/第72期（2024-07-29）.md
  - 第71期（2024-07-27）.md: ./2024/07/第71期（2024-07-27）.md
  - 第70期（2024-07-21）.md: ./2024/07/第70期（2024-07-21）.md
  - 第69期（2024-07-20）.md: ./2024/07/第69期（2024-07-20）.md
  - 第68期（2024-07-19）.md: ./2024/07/第68期（2024-07-19）.md
  - 第67期（2024-07-18）.md: ./2024/07/第67期（2024-07-18）.md
  - 第66期（2024-07-17）.md: ./2024/07/第66期（2024-07-17）.md
  - 第65期（2024-07-11）.md: ./2024/07/第65期（2024-07-11）.md
  - 第64期（2024-07-08）.md: ./2024/07/第64期（2024-07-08）.md
  - 第63期（2024-07-06）.md: ./2024/07/第63期（2024-07-06）.md
  - 第62期（2024-07-04）.md: ./2024/07/第62期（2024-07-04）.md
  - 第61期（2024-06-30）.md: ./2024/06/第61期（2024-06-30）.md
  - 第60期（2024-06-29）.md: ./2024/06/第60期（2024-06-29）.md
  - 第59期（2024-06-25）.md: ./2024/06/第59期（2024-06-25）.md
  - 第58期（2024-06-24）.md: ./2024/06/第58期（2024-06-24）.md
  - 第57期（2024-06-22）.md: ./2024/06/第57期（2024-06-22）.md
  - 第56期（2024-06-21）.md: ./2024/06/第56期（2024-06-21）.md
  - 第55期（2024-06-18）.md: ./2024/06/第55期（2024-06-18）.md
  - 第54期（2024-06-17）.md: ./2024/06/第54期（2024-06-17）.md
  - 第53期（2024-06-15）.md: ./2024/06/第53期（2024-06-15）.md
  - 第52期（2024-06-13）.md: ./2024/06/第52期（2024-06-13）.md
  - 第51期（2024-06-12）.md: ./2024/06/第51期（2024-06-12）.md
  - 第50期（2024-06-10）.md: ./2024/06/第50期（2024-06-10）.md
  - 第49期（2024-06-06）.md: ./2024/06/第49期（2024-06-06）.md
  - 第48期（2024-06-05）.md: ./2024/06/第48期（2024-06-05）.md
  - 第47期（2024-06-03）.md: ./2024/06/第47期（2024-06-03）.md
  - 第46期（2024-06-02）.md: ./2024/06/第46期（2024-06-02）.md
  - 第45期（2024-06-01）.md: ./2024/06/第45期（2024-06-01）.md
  - 第44期（2024-05-31）.md: ./2024/05/第44期（2024-05-31）.md
  - 第43期（2024-05-30）.md: ./2024/05/第43期（2024-05-30）.md
  - 第42期（2024-05-29）.md: ./2024/05/第42期（2024-05-29）.md
  - 第41期（2024-05-28）.md: ./2024/05/第41期（2024-05-28）.md
  - 第40期（2024-05-27）.md: ./2024/05/第40期（2024-05-27）.md
  - 第39期（2024-05-26）.md: ./2024/05/第39期（2024-05-26）.md
  - 第38期（2024-05-24）.md: ./2024/05/第38期（2024-05-24）.md
  - 第37期（2024-05-23）.md: ./2024/05/第37期（2024-05-23）.md
  - 第36期（2024-05-22）.md: ./2024/05/第36期（2024-05-22）.md
  - 第35期（2024-05-21）.md: ./2024/05/第35期（2024-05-21）.md
  - 第34期（2024-05-19）.md: ./2024/05/第34期（2024-05-19）.md
  - 第33期（2024-05-17）.md: ./2024/05/第33期（2024-05-17）.md
  - 第32期（2024-05-14）.md: ./2024/05/第32期（2024-05-14）.md
  - 第31期（2024-05-13）.md: ./2024/05/第31期（2024-05-13）.md
  - 第30期（2024-05-12）.md: ./2024/05/第30期（2024-05-12）.md
  - 第29期（2024-05-08）.md: ./2024/05/第29期（2024-05-08）.md
  - 第28期（2024-05-06）.md: ./2024/05/第28期（2024-05-06）.md
  - 第27期（2024-05-05）.md: ./2024/05/第27期（2024-05-05）.md
  - 第26期（2024-05-03）.md: ./2024/05/第26期（2024-05-03）.md
  - 第25期（2024-04-30）.md: ./2024/04/第25期（2024-04-30）.md
  - 第24期（2024-04-29）.md: ./2024/04/第24期（2024-04-29）.md
  - 第23期（2024-04-27）.md: ./2024/04/第23期（2024-04-27）.md
  - 第22期（2024-04-26）.md: ./2024/04/第22期（2024-04-26）.md
  - 第21期（2024-04-23）.md: ./2024/04/第21期（2024-04-23）.md
  - 第20期（2024-04-22）.md: ./2024/04/第20期（2024-04-22）.md
  - 第19期（2024-04-21）.md: ./2024/04/第19期（2024-04-21）.md
  - 第18期（2024-04-20）.md: ./2024/04/第18期（2024-04-20）.md
  - 第17期（2024-04-19）.md: ./2024/04/第17期（2024-04-19）.md
  - 第16期（2024-04-18）.md: ./2024/04/第16期（2024-04-18）.md
  - 第15期（2024-04-17）.md: ./2024/04/第15期（2024-04-17）.md
  - 第14期（2024-04-15）.md: ./2024/04/第14期（2024-04-15）.md
  - 第13期（2024-04-14）.md: ./2024/04/第13期（2024-04-14）.md
  - 第12期（2024-04-11）.md: ./2024/04/第12期（2024-04-11）.md
  - 第11期（2024-04-10）.md: ./2024/04/第11期（2024-04-10）.md
  - 第10期（2024-04-09）.md: ./2024/04/第10期（2024-04-09）.md
  - 第9期（2024-04-08）.md: ./2024/04/第9期（2024-04-08）.md
  - 第8期（2024-04-07）.md: ./2024/04/第8期（2024-04-07）.md
  - 第7期（2024-04-06）.md: ./2024/04/第7期（2024-04-06）.md
  - 第6期（2024-04-05）.md: ./2024/04/第6期（2024-04-05）.md
  - 第5期（2024-04-04）.md: ./2024/04/第5期（2024-04-04）.md
  - 第4期（2024-04-03）.md: ./2024/04/第4期（2024-04-03）.md
  - 第3期（2024-04-02）.md: ./2024/04/第3期（2024-04-02）.md
  - 第2期（2024-04-01）.md: ./2024/04/第2期（2024-04-01）.md
  - 第1期（2024-03-31）.md: ./2024/第1期（2024-03-31）.md
- 2025 年刊:
  - 第60期（2025-12-18）.md: ./2025/第60期（2025-12-18）.md
  - 第59期（2025-12-16）.md: ./2025/第59期（2025-12-16）.md
  - 第58期（2025-12-13）.md: ./2025/第58期（2025-12-13）.md
  - 第57期（2025-11-18）.md: ./2025/第57期（2025-11-18）.md
  - 第56期（2025-11-17）.md: ./2025/第56期（2025-11-17）.md
  - 第55期（2025-11-16）.md: ./2025/第55期（2025-11-16）.md
  - 第54期（2025-11-15）.md: ./2025/第54期（2025-11-15）.md
  - 第53期（2025-11-14）.md: ./2025/第53期（2025-11-14）.md
  - 第52期（2025-11-11）.md: ./2025/第52期（2025-11-11）.md
  - 第51期（2025-11-07）.md: ./2025/第51期（2025-11-07）.md
  - 第50期（2025-10-23）.md: ./2025/第50期（2025-10-23）.md
  - 第49期（2025-10-15）.md: ./2025/第49期（2025-10-15）.md
  - 第48期（2025-10-11）.md: ./2025/第48期（2025-10-11）.md
  - 第47期（2025-10-09）.md: ./2025/第47期（2025-10-09）.md
  - 第46期（2025-09-16）.md: ./2025/09/第46期（2025-09-16）.md
  - 第45期（2025-09-15）.md: ./2025/09/第45期（2025-09-15）.md
  - 第44期（2025-09-14）.md: ./2025/09/第44期（2025-09-14）.md
  - 第43期（2025-09-04）.md: ./2025/09/第43期（2025-09-04）.md
  - 第42期（2025-08-16）.md: ./2025/08/第42期（2025-08-16）.md
  - 第41期（2025-08-12）.md: ./2025/08/第41期（2025-08-12）.md
  - 第40期（2025-07-31）.md: ./2025/07/第40期（2025-07-31）.md
  - 第39期（2025-07-28）.md: ./2025/07/第39期（2025-07-28）.md
  - 第38期（2025-07-20）.md: ./2025/07/第38期（2025-07-20）.md
  - 第37期（2025-07-18）.md: ./2025/07/第37期（2025-07-18）.md
  - 第36期（2025-06-30）.md: ./2025/06/第36期（2025-06-30）.md
  - 第35期（2025-06-26）.md: ./2025/06/第35期（2025-06-26）.md
  - 第34期（2025-06-19）.md: ./2025/06/第34期（2025-06-19）.md
  - 第33期（2025-06-17）.md: ./2025/06/第33期（2025-06-17）.md
  - 第32期（2025-06-04）.md: ./2025/06/第32期（2025-06-04）.md
  - 第31期（2025-05-29）.md: ./2025/05/第31期（2025-05-29）.md
  - 第30期（2025-05-28）.md: ./2025/05/第30期（2025-05-28）.md
  - 第29期（2025-05-26）.md: ./2025/05/第29期（2025-05-26）.md
  - 第28期（2025-05-25）.md: ./2025/05/第28期（2025-05-25）.md
  - 第27期（2025-05-24）.md: ./2025/05/第27期（2025-05-24）.md
  - 第26期（2025-05-22）.md: ./2025/05/第26期（2025-05-22）.md
  - 第25期（2025-05-17）.md: ./2025/05/第25期（2025-05-17）.md
  - 第24期（2025-04-28）.md: ./2025/04/第24期（2025-04-28）.md
  - 第23期（2025-04-19）.md: ./2025/04/第23期（2025-04-19）.md
  - 第22期（2025-04-12）.md: ./2025/04/第22期（2025-04-12）.md
  - 第21期（2025-04-06）.md: ./2025/04/第21期（2025-04-06）.md
  - 第20期（2025-03-29）.md: ./2025/03/第20期（2025-03-29）.md
  - 第19期（2025-03-27）.md: ./2025/03/第19期（2025-03-27）.md
  - 第18期（2025-03-22）.md: ./2025/03/第18期（2025-03-22）.md
  - 第17期（2025-03-20）.md: ./2025/03/第17期（2025-03-20）.md
  - 第16期（2025-03-19）.md: ./2025/03/第16期（2025-03-19）.md
  - 第15期（2025-03-16）.md: ./2025/03/第15期（2025-03-16）.md
  - 第14期（2025-03-09）.md: ./2025/03/第14期（2025-03-09）.md
  - 第13期（2025-02-26）.md: ./2025/02/第13期（2025-02-26）.md
  - 第12期（2025-02-23）.md: ./2025/02/第12期（2025-02-23）.md
  - 第11期（2025-02-15）.md: ./2025/02/第11期（2025-02-15）.md
  - 第10期（2025-02-13）.md: ./2025/02/第10期（2025-02-13）.md
  - 第9期（2025-02-07）.md: ./2025/02/第9期（2025-02-07）.md
  - 第8期（2025-02-02）.md: ./2025/02/第8期（2025-02-02）.md
  - 第7期（2025-02-01）.md: ./2025/02/第7期（2025-02-01）.md
  - 第6期（2025-01-28）.md: ./2025/01/第6期（2025-01-28）.md
  - 第5期（2025-01-26）.md: ./2025/01/第5期（2025-01-26）.md
  - 第4期（2025-01-19）.md: ./2025/01/第4期（2025-01-19）.md
  - 第3期（2025-01-12）.md: ./2025/01/第3期（2025-01-12）.md
  - 第2期（2025-01-03）.md: ./2025/01/第2期（2025-01-03）.md
  - 第1期（2025-01-02）.md: ./2025/01/第1期（2025-01-02）.md
- Docker 镜像加速: dockerproxy.md
- Github 文件加速: https://www.github-mirrors.zone.id
- chrome webstore: extensions.md
plugins:
- search:
    separator: "[\\s\\u200b\\-]"
- git-revision-date-localized
repo_name: xiaoxuan6/weekly
repo_url: https://github.com/xiaoxuan6/weekly
site_author: xiaoxuan6
site_name: xiaoxuan6's 周刊
theme:
  custom_dir: overrides
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tracking
  - content.code.annotate
  - content.code.copy
  - navigation.sections
  - navigation.top
  - toc.follow
  - search.highlight
  - search.share
  - search.suggest
  - navigation.tabs
  - navigation.tabs.sticky
  language: zh
  name: material
  palette:
  - accent: black
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - accent: indigo
    primary: white
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
