copyright: Copyright &copy; 2023-2024 <a href="https://github.com/xiaoxuan6/weekly">xiaoxuan6's</a>.
extra:
  social:
  - icon: fontawesome/solid/blog
    link: https://xiaoxuan6.github.io
  - icon: fontawesome/brands/github-alt
    link: https://github.com/xiaoxuan6
extra_javascript:
- https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
- static/js/index.js
nav:
- 2024 年刊:
  - 第12期（2024-04-11）.md: ./2024/第12期（2024-04-11）.md
  - 第11期（2024-04-10）.md: ./2024/第11期（2024-04-10）.md
  - 第10期（2024-04-09）.md: ./2024/第10期（2024-04-09）.md
  - 第9期（2024-04-08）.md: ./2024/第9期（2024-04-08）.md
  - 第8期（2024-04-07）.md: ./2024/第8期（2024-04-07）.md
  - 第7期（2024-04-06）.md: ./2024/第7期（2024-04-06）.md
  - 第6期（2024-04-05）.md: ./2024/第6期（2024-04-05）.md
  - 第5期（2024-04-04）.md: ./2024/第5期（2024-04-04）.md
  - 第4期（2024-04-03）.md: ./2024/第4期（2024-04-03）.md
  - 第3期（2024-04-02）.md: ./2024/第3期（2024-04-02）.md
  - 第2期（2024-04-01）.md: ./2024/第2期（2024-04-01）.md
  - 第1期（2024-03-31）.md: ./2024/第1期（2024-03-31）.md
plugins:
- search:
    separator: "[\\s\\u200b\\-]"
- git-revision-date-localized
repo_name: xiaoxuan6/weekly
repo_url: https://github.com/xiaoxuan6/weekly
site_author: xiaoxuan6
site_name: xiaoxuan6's 周刊
theme:
  custom_dir: overrides
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tracking
  - content.code.annotate
  - content.code.copy
  - navigation.sections
  - navigation.top
  - toc.follow
  - search.highlight
  - search.share
  - search.suggest
  - navigation.tabs
  - navigation.tabs.sticky
  language: zh
  name: material
  palette:
  - accent: black
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - accent: indigo
    primary: white
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
