copyright: Copyright &copy; 2023-2024 <a href="https://github.com/xiaoxuan6/weekly">xiaoxuan6's</a>.
extra:
  social:
  - icon: fontawesome/solid/blog
    link: https://xiaoxuan6.github.io
  - icon: fontawesome/brands/github-alt
    link: https://github.com/xiaoxuan6
extra_javascript:
- https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js
- static/js/index.js
nav:
- 2024 年刊:
  - 第2期（2024-04-01）.md: ./2024/第2期（2024-04-01）.md
  - 第1期（2024-03-31）.md: ./2024/第1期（2024-03-31）.md
plugins:
- search
- git-revision-date-localized
repo_name: xiaoxuan6/weekly
repo_url: https://github.com/xiaoxuan6/weekly
site_author: xiaoxuan6
site_name: xiaoxuan6's 周刊
theme:
  custom_dir: overrides
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tracking
  - content.code.annotate
  - content.code.copy
  - navigation.sections
  - navigation.top
  - toc.follow
  - search.highlight
  - search.share
  - search.suggest
  - navigation.tabs
  - navigation.tabs.sticky
  language: zh
  name: material
  palette:
  - accent: black
    primary: black
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - accent: indigo
    primary: white
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  search_index_only: true
